// resources/js/react/laravel-mix/MessageList.jsx
import React, { useState, useRef, useEffect } from 'react';
import MessageItem from './MessageItem';
import TypingIndicator from './TypingIndicator';
import './MessageList.css';

const MessageList = ({
  messages = [],
  currentUserId = null,
  loading = false,
  loadingMore = false,
  loadingText = 'Loading messages...',
  emptyText = 'No messages yet',
  typingUsers = [],
  autoScroll = true,
  onReactionClick,
  onThreadClick,
  onMessageClick,
  onLoadMore
}) => {
  const messageListRef = useRef(null);
  const [scrolledToBottom, setScrolledToBottom] = useState(true);
  const [lastMessageSenderId, setLastMessageSenderId] = useState(null);
  const [lastMessageTimestamp, setLastMessageTimestamp] = useState(null);

  // Group messages by date
  const messageGroups = (() => {
    const groups = [];
    let currentDate = null;
    let currentGroup = null;

    messages.forEach(message => {
      const messageDate = new Date(message.createdAt);
      const dateString = formatMessageDate(messageDate);

      if (dateString !== currentDate) {
        currentDate = dateString;
        currentGroup = {
          date: dateString,
          messages: []
        };
        groups.push(currentGroup);
      }

      currentGroup.messages.push(message);
    });

    return groups;
  })();

  // Format message date for display
  const formatMessageDate = (date) => {
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);

    if (date.toDateString() === today.toDateString()) {
      return 'Today';
    } else if (date.toDateString() === yesterday.toDateString()) {
      return 'Yesterday';
    } else {
      return date.toLocaleDateString(undefined, {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    }
  };

  // Determine if avatar should be shown for this message
  const shouldShowAvatar = (message) => {
    // Always show avatar for the first message in a group
    if (lastMessageSenderId !== message.sender.id) {
      setLastMessageSenderId(message.sender.id);
      setLastMessageTimestamp(message.createdAt);
      return true;
    }

    // Show avatar if messages are more than 5 minutes apart
    const currentTime = new Date(message.createdAt).getTime();
    const lastTime = new Date(lastMessageTimestamp).getTime();
    const timeDiff = (currentTime - lastTime) / (1000 * 60); // difference in minutes

    setLastMessageTimestamp(message.createdAt);

    return timeDiff > 5;
  };

  // Determine if this message is consecutive (from same sender with small time gap)
  const isConsecutiveMessage = (message) => {
    return lastMessageSenderId === message.sender.id;
  };

  // Scroll to the bottom of the message list
  const scrollToBottom = () => {
    if (messageListRef.current) {
      messageListRef.current.scrollTop = messageListRef.current.scrollHeight;
    }
  };

  // Handle scroll event to detect when user scrolls away from bottom
  const handleScroll = () => {
    if (messageListRef.current) {
      const { scrollTop, scrollHeight, clientHeight } = messageListRef.current;
      const atBottom = scrollHeight - scrollTop - clientHeight < 50;

      setScrolledToBottom(atBottom);

      // Emit scroll to top event for infinite loading
      if (scrollTop < 50 && !loading && !loadingMore) {
        onLoadMore && onLoadMore();
      }
    }
  };

  // Scroll to bottom when messages change
  useEffect(() => {
    if (autoScroll && scrolledToBottom) {
      scrollToBottom();
    }
  }, [messages, autoScroll, scrolledToBottom]);

  // Set up scroll event listener
  useEffect(() => {
    const messageList = messageListRef.current;
    if (messageList) {
      messageList.addEventListener('scroll', handleScroll);
    }

    // Initial scroll to bottom
    scrollToBottom();

    return () => {
      if (messageList) {
        messageList.removeEventListener('scroll', handleScroll);
      }
    };
  }, []);

  return (
    <div className="message-list" ref={messageListRef}>
      {loading && messages.length === 0 ? (
        <div className="message-list__loading">
          <div className="message-list__loading-spinner"></div>
          <div className="message-list__loading-text">{loadingText}</div>
        </div>
      ) : messages.length === 0 ? (
        <div className="message-list__empty">
          {emptyText}
        </div>
      ) : (
        <div className="message-list__container">
          {loadingMore && (
            <div className="message-list__loading-more">
              <div className="message-list__loading-spinner"></div>
            </div>
          )}

          {messageGroups.map((group, index) => (
            <div key={index} className="message-list__group">
              <div className="message-list__date-divider">
                <span className="message-list__date-text">{group.date}</span>
              </div>

              {group.messages.map(message => (
                <MessageItem
                  key={message.id}
                  message={message}
                  currentUserId={currentUserId}
                  showAvatar={shouldShowAvatar(message)}
                  consecutive={isConsecutiveMessage(message)}
                  onReactionClick={onReactionClick}
                  onThreadClick={onThreadClick}
                  onMessageClick={onMessageClick}
                />
              ))}
            </div>
          ))}

          {typingUsers.length > 0 && (
            <div className="message-list__typing">
              <TypingIndicator users={typingUsers} />
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default MessageList;

// resources/js/vue/laravel-mix/MessageList.vue
<template>
  <div class="message-list" ref="messageList">
    <div v-if="loading && messages.length === 0" class="message-list__loading">
      <div class="message-list__loading-spinner"></div>
      <div class="message-list__loading-text">{{ loadingText }}</div>
    </div>
    <div v-else-if="messages.length === 0" class="message-list__empty">
      {{ emptyText }}
    </div>
    <div v-else class="message-list__container">
      <div v-if="loadingMore" class="message-list__loading-more">
        <div class="message-list__loading-spinner"></div>
      </div>
      
      <div v-for="(group, index) in messageGroups" :key="index" class="message-list__group">
        <div class="message-list__date-divider">
          <span class="message-list__date-text">{{ group.date }}</span>
        </div>
        
        <message-item
          v-for="message in group.messages"
          :key="message.id"
          :message="message"
          :current-user-id="currentUserId"
          :show-avatar="shouldShowAvatar(message)"
          :consecutive="isConsecutiveMessage(message)"
          @reaction-click="handleReactionClick"
          @thread-click="handleThreadClick"
          @message-click="handleMessageClick"
        />
      </div>
      
      <div v-if="typingUsers.length > 0" class="message-list__typing">
        <typing-indicator :users="typingUsers" />
      </div>
    </div>
  </div>
</template>

<script>
import MessageItem from './MessageItem.vue';
import TypingIndicator from './TypingIndicator.vue';

export default {
  name: 'MessageList',
  components: {
    MessageItem,
    TypingIndicator
  },
  props: {
    /**
     * Array of message objects
     */
    messages: {
      type: Array,
      default: () => []
    },
    /**
     * Current user ID
     */
    currentUserId: {
      type: [String, Number],
      default: null
    },
    /**
     * Whether messages are currently loading
     */
    loading: {
      type: Boolean,
      default: false
    },
    /**
     * Whether more messages are being loaded (for infinite scroll)
     */
    loadingMore: {
      type: Boolean,
      default: false
    },
    /**
     * Text to display while loading
     */
    loadingText: {
      type: String,
      default: 'Loading messages...'
    },
    /**
     * Text to display when there are no messages
     */
    emptyText: {
      type: String,
      default: 'No messages yet'
    },
    /**
     * Array of users who are currently typing
     */
    typingUsers: {
      type: Array,
      default: () => []
    },
    /**
     * Whether to automatically scroll to the bottom on new messages
     */
    autoScroll: {
      type: Boolean,
      default: true
    }
  },
  data() {
    return {
      lastMessageSenderId: null,
      lastMessageTimestamp: null,
      scrolledToBottom: true
    };
  },
  computed: {
    /**
     * Group messages by date
     */
    messageGroups() {
      const groups = [];
      let currentDate = null;
      let currentGroup = null;
      
      this.messages.forEach(message => {
        const messageDate = new Date(message.createdAt);
        const dateString = this.formatMessageDate(messageDate);
        
        if (dateString !== currentDate) {
          currentDate = dateString;
          currentGroup = {
            date: dateString,
            messages: []
          };
          groups.push(currentGroup);
        }
        
        currentGroup.messages.push(message);
      });
      
      return groups;
    }
  },
  watch: {
    /**
     * Watch for changes in messages to scroll to bottom if needed
     */
    messages: {
      handler() {
        if (this.autoScroll && this.scrolledToBottom) {
          this.$nextTick(() => {
            this.scrollToBottom();
          });
        }
      },
      deep: true
    }
  },
  mounted() {
    // Initial scroll to bottom
    this.$nextTick(() => {
      this.scrollToBottom();
    });
    
    // Add scroll event listener to detect when user scrolls away from bottom
    const messageList = this.$refs.messageList;
    if (messageList) {
      messageList.addEventListener('scroll', this.handleScroll);
    }
  },
  beforeUnmount() {
    // Remove scroll event listener
    const messageList = this.$refs.messageList;
    if (messageList) {
      messageList.removeEventListener('scroll', this.handleScroll);
    }
  },
  methods: {
    /**
     * Format message date for display
     */
    formatMessageDate(date) {
      const today = new Date();
      const yesterday = new Date(today);
      yesterday.setDate(yesterday.getDate() - 1);
      
      if (date.toDateString() === today.toDateString()) {
        return 'Today';
      } else if (date.toDateString() === yesterday.toDateString()) {
        return 'Yesterday';
      } else {
        return date.toLocaleDateString(undefined, {
          weekday: 'long',
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        });
      }
    },
    /**
     * Determine if avatar should be shown for this message
     */
    shouldShowAvatar(message) {
      // Always show avatar for the first message in a group
      if (this.lastMessageSenderId !== message.sender.id) {
        this.lastMessageSenderId = message.sender.id;
        this.lastMessageTimestamp = message.createdAt;
        return true;
      }
      
      // Show avatar if messages are more than 5 minutes apart
      const currentTime = new Date(message.createdAt).getTime();
      const lastTime = new Date(this.lastMessageTimestamp).getTime();
      const timeDiff = (currentTime - lastTime) / (1000 * 60); // difference in minutes
      
      this.lastMessageTimestamp = message.createdAt;
      
      return timeDiff > 5;
    },
    /**
     * Determine if this message is consecutive (from same sender with small time gap)
     */
    isConsecutiveMessage(message) {
      return this.lastMessageSenderId === message.sender.id;
    },
    /**
     * Handle reaction click event
     */
    handleReactionClick(message, reaction) {
      this.$emit('reaction-click', message, reaction);
    },
    /**
     * Handle thread click event
     */
    handleThreadClick(message) {
      this.$emit('thread-click', message);
    },
    /**
     * Handle message click event
     */
    handleMessageClick(message) {
      this.$emit('message-click', message);
    },
    /**
     * Scroll to the bottom of the message list
     */
    scrollToBottom() {
      const messageList = this.$refs.messageList;
      if (messageList) {
        messageList.scrollTop = messageList.scrollHeight;
      }
    },
    /**
     * Handle scroll event to detect when user scrolls away from bottom
     */
    handleScroll() {
      const messageList = this.$refs.messageList;
      if (messageList) {
        const { scrollTop, scrollHeight, clientHeight } = messageList;
        const atBottom = scrollHeight - scrollTop - clientHeight < 50;
        
        this.scrolledToBottom = atBottom;
        
        // Emit scroll to top event for infinite loading
        if (scrollTop < 50 && !this.loading && !this.loadingMore) {
          this.$emit('load-more');
        }
      }
    }
  }
};
</script>

<style scoped>
.message-list {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow-y: auto;
  padding: 16px;
  background-color: #fff;
}

.message-list__loading,
.message-list__empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #666;
  text-align: center;
}

.message-list__loading-spinner {
  width: 30px;
  height: 30px;
  border: 3px solid rgba(0, 0, 0, 0.1);
  border-radius: 50%;
  border-top-color: #3490dc;
  animation: spin 1s ease-in-out infinite;
  margin-bottom: 10px;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.message-list__container {
  display: flex;
  flex-direction: column;
  min-height: 0;
  flex: 1;
}

.message-list__loading-more {
  display: flex;
  justify-content: center;
  padding: 10px 0;
}

.message-list__group {
  margin-bottom: 16px;
}

.message-list__date-divider {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 16px 0;
  position: relative;
}

.message-list__date-divider::before {
  content: '';
  position: absolute;
  left: 0;
  right: 0;
  height: 1px;
  background-color: #e0e0e0;
  z-index: 1;
}

.message-list__date-text {
  background-color: #fff;
  padding: 0 10px;
  font-size: 0.8rem;
  color: #666;
  position: relative;
  z-index: 2;
}

.message-list__typing {
  margin-top: 8px;
}
</style>
